#version: '3'
#
#services:
#  db:
#    image: postgres:15.3-alpine
#    container_name: db
#    volumes:
#      - pg_data:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
#    env_file:
#      - ./.env
#    environment:
#      - DB_NAME=$DB_NAME
#      - DB_USER=$DB_USER
#      - DB_PASSWORD=$DB_PASSWORD
#      - DB_HOST=$DB_HOST
#      - DB_PORT=$DB_PORT
#
#
#  django:
#    build: .
#    container_name: django
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/app
#    entrypoint: /app/entrypoint.sh
#    ports:
#      - '8000:8000'
#    env_file:
#      - ./.env
#    environment:
#      - DB_NAME=$DB_NAME
#      - DB_USER=$DB_USER
#      - DB_PASSWORD=$DB_PASSWORD
#      - DB_HOST=$DB_HOST
#      - DB_PORT=$DB_PORT
#    depends_on:
#      - db
#
#
#volumes:
#  pg_data:
